name: segue_coleta
description: "Aplicativo Segue Coleta"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.12.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  table_calendar: ^3.1.2
  flutter_localizations: # ✅ Adicione essa linha
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  # ✅ Caminho das imagens (logo etc)
  assets:
    - assets/images/