// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzpotfAfLR3HHlTEIwyYhb4GnWEqTATsQ',
    appId: '1:554380075684:web:2c18596f038b4bf21d7c31',
    messagingSenderId: '554380075684',
    projectId: 'segue-coleta',
    authDomain: 'segue-coleta.firebaseapp.com',
    storageBucket: 'segue-coleta.firebasestorage.app',
    measurementId: 'G-VPD5H102ZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfY0sCoZkKbkLyIBURPF2Cg_6cP09bOWY',
    appId: '1:554380075684:android:b049041a6da8208b1d7c31',
    messagingSenderId: '554380075684',
    projectId: 'segue-coleta',
    storageBucket: 'segue-coleta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1YWsOMWbjhvnMcc-3IlCOFDgjdjNicMY',
    appId: '1:554380075684:ios:5e9c675132ed1d641d7c31',
    messagingSenderId: '554380075684',
    projectId: 'segue-coleta',
    storageBucket: 'segue-coleta.firebasestorage.app',
    iosBundleId: 'com.example.segueColeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1YWsOMWbjhvnMcc-3IlCOFDgjdjNicMY',
    appId: '1:554380075684:ios:5e9c675132ed1d641d7c31',
    messagingSenderId: '554380075684',
    projectId: 'segue-coleta',
    storageBucket: 'segue-coleta.firebasestorage.app',
    iosBundleId: 'com.example.segueColeta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzpotfAfLR3HHlTEIwyYhb4GnWEqTATsQ',
    appId: '1:554380075684:web:c88d7569777f7bd61d7c31',
    messagingSenderId: '554380075684',
    projectId: 'segue-coleta',
    authDomain: 'segue-coleta.firebaseapp.com',
    storageBucket: 'segue-coleta.firebasestorage.app',
    measurementId: 'G-9K44C7Y6LH',
  );
}
